engines:
  duplication:
    exclude_paths:
      - '**/test/**'
  metric:
    exclude_paths:
      - '**/test/**'
  clang-tidy:
    exclude_paths:
      - '**/test/test/**'
exclude_paths:
  - '**/dist/**'
