name: 'Run Action'
author: 'Michael Beckh'
description: 'Run executables from a previous build'
inputs:
  solution-path:
    description: 'The relative path of the solution file'
    required: false
    default: '.'
  projects:
    description: 'The name(s) of the project(s), separated by comma, semicolon or newline'
    required: true
  configuration:
    description: 'The name of the configuration which was built'
    required: true
  platform:
    description: 'The platform for which was built'
    required: false
    default: 'x64'
runs:
  using: 'node12'
  main: './run.js'
