name: test

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Testing
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run 'build' action
      uses: ./actions/build
      with:
        solution-path: actions/test
        projects: main, main_Test
        configuration: ${{ matrix.configuration }}

    - name: Run 'run' action
      if: matrix.configuration != 'Debug'
      uses: ./actions/run
      with:
        solution-path: actions/test
        projects: main_Test
        configuration: ${{ matrix.configuration }}

    - name: Run 'coverage' action
      if: matrix.configuration == 'Debug'
      uses: ./actions/coverage
      with:
        solution-path: actions/test
        projects: main_Test
        configuration: ${{ matrix.configuration }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        codacy-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}

    - name: Save output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: .mbeckh/output

    - name: Save coverage
      if: matrix.configuration == 'Debug'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: .mbeckh/coverage

  analyze:
    name: Analyzing
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run 'analyze-clang-tidy' action
      uses: ./actions/analyze-clang-tidy
      with:
        id: default

    - name: Save logs
      uses: actions/upload-artifact@v2
      with:
        name: clang-tidy
        path: .mbeckh/clang-tidy-*.log

    - name: Run 'analyze-report' action
      uses: ./actions/analyze-report
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        codacy-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}
