name: test

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Testing
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run 'build' action
      uses: ./actions/build
      with:
        solution-path: actions/test
        projects: main, main_Test
        configuration: Debug

    - name: Run 'run' action
      uses: ./actions/run
      with:
        solution-path: actions/test
        projects: main_Test
        configuration: Debug

    - name: Run 'coverage' action
      uses: ./actions/coverage
      with:
        solution-path: actions/test
        projects: main_Test
        configuration: Debug
        codacy-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}

  analyze:
    name: Analyzing
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run 'analyze' action
      uses: ./actions/analyze
      with:
        solution-path: actions/test
        projects: main
        configuration: Debug
        codacy-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}
